// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1hei3Dw8rb-GCmzvx41BqHwPHxJzZoRI',
    appId: '1:915353570557:web:6b2c15c1376738b0cac294',
    messagingSenderId: '915353570557',
    projectId: 'gemnichat',
    authDomain: 'gemnichat.firebaseapp.com',
    storageBucket: 'gemnichat.firebasestorage.app',
    measurementId: 'G-0WVNT49JNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxgWo-FDwtuOegPusPLFAlOSSzCxWFs7g',
    appId: '1:915353570557:android:9478da4e84f58bb9cac294',
    messagingSenderId: '915353570557',
    projectId: 'gemnichat',
    storageBucket: 'gemnichat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBidceM7ME0JIWVulhMaXYSHcO1BoOCCW4',
    appId: '1:915353570557:ios:39df761ea5a91fd1cac294',
    messagingSenderId: '915353570557',
    projectId: 'gemnichat',
    storageBucket: 'gemnichat.firebasestorage.app',
    iosClientId: '915353570557-fpga292sc3ajokp9dpjbmoa96b8ln87i.apps.googleusercontent.com',
    iosBundleId: 'com.example.gemnichatApp',
  );
}
